version: '2'
services:
  core:
    build: ./core/.
    ports:
      - "3000:3000"
    volumes:
      - ./core/:/usr/api
  blinkie:
    build: ./blinkie/.
    ports:
      - "3001:3001"
    links:
      - core
